### ISSUE TITLE
Why not AES-CTR + HMAC?

### ISSUE THREAD

**Issue by Xeoncross** [minio/sio#26]
What issue(s) is sio solving by implementing the DARE format using the more complex custom mixture of GCM (+ chunk order integrity) instead of simply using CTR + HMAC across the whole stream like [xeodou/aesf](https://github.com/xeodou/aesf) or the popular [odeke-em/drive](https://github.com/odeke-em/drive/tree/master/src/dcrypto) client [(wiki)](https://github.com/odeke-em/drive/wiki/End-to-End-Encryption)?

**Comment by kennylevinsen** [comment]
There is nothing custom or complex about using AES-GCM over AES-CTR + HMAC-SHA2_256. AES-GCM is *simpler* than AES-CTR + HMAC-SHA2_256.

To let the code speak for itself, here is AES-CTR in Go:
```go
func NewAESCTR(key, iv []byte) (cipher.Stream, error) {
	aes256, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewCTR(aes256, iv) 
}
```

The above has no authentication. However, if we change two lines, we get a fully authenticated crypto device (including verification on decrypt):
```go
func NewAESGCM(key []byte) (cipher.AEAD, error) {
	aes256, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(aes256) 
}
```

For ChaCha20-Poly1305, the above is reduce to a single line.

This simplicity is the primary argument for using an AEAD: The authentication is an integral part of the algorithm, removing the need to juggle multiple cryptographic primitives and potentially misimplement or even miss the authentication part (you would be surprised to see how many people implement HMAC-SHA2_256 as either SHA2_256(key + data) or SHA2_256(data + key)...).

There is no good argument *against* using an AEAD. When available, they should be preferred. And when it is not available, effort should be put into correcting this.

**Comment by Xeoncross** [comment]
I wasn't talking about GCM vs CTR for small blobs. I'm talking about large blobs that don't fit into memory (and/or streams). Otherwise what is the point of sio since GCM already works fine for those?

However, the go implementation of GCM does not support _streaming_ and requires the whole blob to be loaded into memory. The CTR implementation does not.

So my question is why did you wrap GCM with chunk order integrity instead of simply using CTR + HMAC across the whole stream?

**Comment by kennylevinsen** [comment]
Sorry, this is a bit long.

> So my question is why did you wrap GCM with chunk order integrity instead of simply using CTR + HMAC across the whole stream?

Ah, okay. First of all, that AEAD can only be run on full in-memory blob is an unfortunate side-effect of the Go AEAD interface. It is not related to the algorithm at all. It would be nice with a more flexible interface consisting of an io.Writer and a Finalize method, but that discussion belongs to a different forum.

You might have misunderstood this limitation as being the reason DARE chunks packets. Without chunking, the receiver would have to wait until *all* data was received in order to verify the authentication, as a receiver must *never* look at or perform actions based any unverified data structure. This is exactly the kind of behavior you voice concerns about, and it is flat out unacceptable.

With unchunked AES-CTR + HMAC, this might mean keeping absurd amounts of data in memory before the receiver can perform any actions on it, such as committing a received file to disk. With the chunking specified in the DARE protocol, a receiver will at most have to wait for 64KB before it can verify a chunk, allowing it to simulate a streaming behavior while maintaining authentication guarantees.

Thus, the chunking protocol is required none the less, and the only superficial difference between AES-CTR + HMAC and AES-GCM would be that AES-GCM is significantly simpler to implement.

> Another way to phrase the question is, what does minio/sio offer that CTR + (encrypt-then-HMAC) does not?

minio/sio is an *implementation* of a *protocol* that use *cryptographic primitives*, whereas AES-CTR and HMAC-SHA2_256 are just cryptographic primitives. minio/sio is comparable to other protocol implementations like libsodium or Openssl, in that minio/sio implements DARE, libsodium implements NaCl, and OpenSSL implements TLS, all of which specify some use of crypto.

Thus, what you appear to be asking is "what does a finished protocol implementation offer over rolling my own homemade cryptographic protocol (like TLS, NaCl or Dare) and implementing it myself (like done by OpenSSL, libsodium or minio/sio)?".

The answer to that should be quite clear: Designing cryptographic protocols that are safe requires an immense amount of work, and is quite easy to screw up even before you get around to implementing it. By using an existing protocol like NaCl and TLS, you are using something that has gone by extreme scrutiny by cryptographers. Likewise, by using existing implementations, you are using something that has gone through scrutiny by a number of programmers larger than 1.

My rule of thumb is that if your project is *not* a new cryptographic protocol due to thinking you can deliver something new to the scene, then you do *not* create such new protocol, but instead use existing tech. If you do need a new one, make it as its own public project that you depend on. Don't just keep it hidden. And for the love of all that is sacred, never make such a protocol proprietary unless you really want to shoot yourself in the foot.

**Comment by Xeoncross** [comment]
> Without chunking, the receiver would have to wait until all data was received in order to verify the authentication, as a receiver must never look at or perform actions based any unverified data structure. 

Thank you for your replies. I realized after asking this question I was not thinking straight about streaming video vs streaming file chunks. Video needs to be immediately ready (low-latency) so AHEAD on small blobs is really the only choice. You can't put a HMAC at the end of of a 24hr live video stream.

I guess this leaves file encryption/decryption as the only reason to use possibly use CTR to avoid the extra space/time used by an encryption header every # bytes (64k in your case).

**Comment by kennylevinsen** [comment]
Yes, and in the case of file encryption, is is not unthinkable to consider a system that starts writing a file to disk as it decrypt it, even though it has not yet been validated.

However, it is important that one treats data as *invalid* and *malicious* until the verification is done. If you write to disk before verifying the data, an adversary could burn all your storage by spamming your service with endless streams of garbage that you would happily write to disk, even though there is no valid authentication.

Thus, even for file storage, it is not a good idea to write anything before the data is verified, which make chunking the right solution.

(Also, note that the DARE packet header for 64k only presents a 0.25% overhead. That should be quite acceptable for basically all use-cases.)

**Comment by Xeoncross** [comment]
Taking file streams from a client is a great example problem. The mediation for that would be to stream data to temp files which are removed if invalid or moved if valid. However, it does mean that the whole request body must be read before the connection could be closed wasting a lot of disk and network I/O. Certainly not worth tiny the overhead sio might add.

In addition, it seems Go has optimized assembly code for GCM, so it is probably faster anyway.

**Comment by aead** [comment]
@Xeoncross 
The main purpose of DARE is - as already mentioned - to provide encrypted & authenticated streaming. This means that you can encrypt and authenticate an (almost arbitrary long) data stream such that the decryption **and** integrity verification consumes just a **constant** amount of RAM.
Notice that this is not true for any classical AEAD (like AES-GCM, ChaCha20Poly1305 or AES-CTR-HMAC). Those AEAD schemes require `O(n)` space where `n` is the size of plaintext. This leads to serious problems in applications like (video) streaming or forwarding data like a proxy (as already mentioned). Processing decrypted **but** not-yet verified data can be a security issue and should be avoided.

DARE tries to solve this problem.

BTW: The Go approach of allowing authenticated encryption / decryption only in RAM is a feature, not a bug. It avoids exactly the problem described here. Using an AEAD in a streaming mode may lead to security issues and is a subtle pitfall.


@kennylevinsen 

>To give you an idea of how easy it is to mess up, the DARE 1.0 spec mishandled nonce's by reusing them for each block, which invalidates the security guarantees of the underlying AEAD ciphers.

Can you explain that in detail? AFAICT the nonce is handled properly in DARE 1.0.

**Comment by kennylevinsen** [comment]
@aead As mentioned in my other issue, I entirely misinterpreted the situation due to confusion caused by the use of the word "nonce" in the spec, method naming in the code, as well as a v2 implementation that made it look like it had now "been fixed". Let's keep that in my other issue.

@Xeoncross Just to be clear, the DARE 1.0 spec is actually A-OK with regards to nonce.

**Comment by aead** [comment]
Closing this since the question seems to be answered.
@Xeoncross Please reopen if you think this is not resolved.
