### ISSUE TITLE
v1 interfaces should contain warning about flawed crypto

### ISSUE THREAD

**Issue by kennylevinsen** [minio/sio#27]
DARE 1.0 contained a flaw that reused a nonce multiple times for the same key, which invalidate the security guarantees of the underlying primitives.

This is changed in DARE 2.0 so that the nonce contains a 32-bit stream-local sequence counter, thus ensuring that multiple packets in the same stream will not contain the same nonce as long as the 32-bit counter does not overflow. minio/sio implements both DARE 1.0 and DARE 2.0 (supposedly for compatibility).

Looking in the readme, documentation and in the code, I found nowhere that stated that DARE 1.0 is insecure, and that it should only be used to decrypt legacy content if the lack of security is acceptable. It is of outmost importance to make such a flaw clear, and state it in all those three locations at the very least. Preferably at the very top of the README in the coming time until DARE 2.0 has gotten some age.

As a side-note, the DARE.md file still only mention DARE 1.0. An up to date spec would be nice.

**Comment by harshavardhana** [comment]
Thanks for pointing it out @kennylevinsen we will add a NOTE about why we moved from 1.0 to 2.0

**Comment by aead** [comment]
>DARE 1.0 contained a flaw that reused a nonce multiple times for the same key, which invalidate the security guarantees of the underlying primitives.

@kennylevinsen Can you explain why you think this is the case?

>This is changed in DARE 2.0 so that the nonce contains a 32-bit stream-local sequence counter, thus ensuring that multiple packets in the same stream will not contain the same nonce as long as the 32-bit counter does not overflow. minio/sio implements both DARE 1.0 and DARE 2.0 (supposedly for compatibility).

Also DARE 1.0 contains a 32 bit counter. It is mixed differently into the nonce. However this "just" provides slightly better guarantees (nonce collision bounds) if a secret key is **reused**.

AFAICT the only significant difference between 1.0 and 2.0 is that 2.0 prevents dropping packages from the end of the stream.

**Comment by kennylevinsen** [comment]
AH, I apologize, I have made a mistake as a result of several confusing bits chained together:

I was reading this section of the spec:
> The *nonce* should be a random value for each data stream and should be kept constant for all its packages.

As well as this part of the code, which looks like it is extracting the *nonce* field of the header and feeding it directly as nonce to the cipher.AEAD:
```go
func (ae *authEncV10) Seal(dst, src []byte) {
	header := headerV10(dst[:headerSize])
	header.SetVersion()
	header.SetCipher(ae.CipherID)
	header.SetLen(len(src))
	header.SetSequenceNumber(ae.SeqNum)
	header.SetRand(ae.RandVal)
	ae.Cipher.Seal(dst[headerSize:headerSize], header.Nonce(), src, header.AddData())
	ae.SeqNum++
}
```

I just now realize that despite its name, header.Nonce() returns both the header nonce *and* the sequence numbe rby means of slicing the header, and that the spec later defines the nonce for the *cipher* as such. The implementation of authEncV20 set the confusion in stone by making it appear that mixing in the sequence number was added later.

Please disregard this issue. I apologize for any inconvenience caused. However, if I may, I would suggest the following changes to avoid the confusion I do find to be slightly fair:

- Consider not calling the header method "Nonce()", as it looks like a getter for the field of the same name.
- Consider not using the word "nonce" in other contexts than what is fed as nonce to the ciphers. The terminology is conflicting, and the word is quite strongly tied to its use for the cryptographic primitives themselves. Furthermore, considering that the 'nonce' field is kept static for a stream, I think "stream serial" would be a more appropriate term.

Again, I apologize for any inconvenience caused by me reading the code too fast at night.

**Comment by kennylevinsen** [comment]
(I am closing this to avoid having this issue bring a wrong message, but I am still looking at the discussion.)

**Comment by aead** [comment]
@kennylevinsen No problem :smiley:

**Comment by aead** [comment]
@kennylevinsen No problem at all :smiley: 

I guess the confusing comes from the fact that there are two "nonces". The first one - also referred as `random value / randVal` is the random value used for the entire data stream to limit damage caused by key-reuse. The second "nonce" is a "real" nonce in terms of cryptography. It is used as input to the AEAD scheme and is 12 bytes long (v1.0 and v2.0). So for DARE 1.0 the en/decryption nonce = `random value || sequence number` while for DARE 2.0 the en/decryption nonce = `random value ^ sequence number.
So I think the `header.Nonce()` function seems reasonable to me. The problem is that the random value for the entire data stream is  also named nonce which leads to this confusion.
For DARE 2.0 the `header.Nonce()` function is semantically different from 1.0 - which I agree looks confusing. 
I will add this to TODO as something we can improve - thanks!

I'm also working on a *scientific* specification of 2.0 which provides much more details and may could avoid such confusion - but this task got deferred because of lack of time, but I'm on that.
