### ISSUE TITLE
Compatibility with Raspberry Pi

### ISSUE THREAD

**Issue by eacp** [minio/sio#35]
Hello. I’m building a tool in go that uses this to create encrypted backups of data. In the source code we have aesSuported flag, which checks stuff from the CPU. However, if the GOARCH is ARM, what would happen then?

**Comment by aead** [comment]
> In the source code we have aesSuported flag

The `sio` package does this internally as well - and selects `AES-GCM` only on `x86/amd64` when AES-NI is available or on `s390x`. The reason is that the generic standard library implementation of AES-GCM is not resistant against side-channel attacks. However, IIRC an ARM64 asm. implementation has been merged - so we could default to AES-GCM on ARM64 as well (if hardware support is available).  
Otherwise, `sio` will default to `ChaCha20Poly1305`. Anyway, you can specify the used AEAD cipher directly see e.g.: [`Config.CipherSuites = []byte{sio.AES_256_GCM}`](https://github.com/minio/sio/blob/master/sio.go#L110)

FYI: For new projects I would recommend using an improved version: [`secure-io/sio`](https://github.com/secure-io/sio-go) since it is provable secure.  
(i.e. `AES is "secure"` ==> `AES-GCM is "secure"` ==> [`secure-io/sio`](https://github.com/secure-io/sio-go)`is "secure"`)

**Comment by eacp** [comment]
> FYI: For new projects I would recommend to use an improved version: [`secure-io/sio`](https://github.com/secure-io/sio-go) since it is provable secure.
> (i.e. `AES is "secure"` ==> `AES-GCM is "secure"` ==> [`secure-io/sio`](https://github.com/secure-io/sio-go)`is "secure"`)

Does this new version support the DARE format? I read about it in this repository and I really liked it, specially because it allows the encryption of large files (eg. 2 GB) without loading them in memory.

**Comment by aead** [comment]
> Does this new version support the DARE format?

The DARE format is a specialization of a `secure channel construction` (as format). So, [`secure-io/sio`](https://github.com/secure-io/sio-go) does not support the DARE format such that you can encrypt e.g. a file with `minio/sio` and successfully decrypt it again with `secure-io/sio-go` - **but** it's applicable to the same scenarios. You can encrypt large files without loading  them to memory using `secure-io/sio-go`. It's basically designed for that :smiley: 

So, you can use `secure-io/sio-go` as replacement for `minio/sio` for any use case (AFAICS) and achieve provable security + better performance.

**Comment by kannappanr** [comment]
@eacp Closing this issue as answered. Please feel free to reach out to us if you have further questions
